apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horseproject
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/unlimited-excellence/gitops.git
    path: manifests/horseproject
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: horseproject
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
